_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 6
                - 35
                - 53
                - 55
            "2":
                - 5
                - 6
                - 35
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 3
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": windows-amd64
